### ISSUE TITLE
TSC Meeting Minutes (05/05/2020)

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/community#10]
Agenda: https://github.com/StackStorm/discussions/issues/5
Attendees: @mickmcgrath13 @blag @nmaludy @armab @punkrokk 

Minutes:

Next meeting is June 2, 2020 ( @blag )

- @punkrokk provided LF updates and next steps
- @punkrokk & @armab provided FOSS updates
- @punkrokk suggested that ST2 provide more clarity around how to characterize recommending, encouraging and promoting community members to become contributors, maintainers, etc. Intent was to seed a conversation for the near future. 
- @armab provided a review on the v3.2 release process, and noted the desire to to more releases more often. Kudos was given to all. It was an all around rock star effort by everyone to get v3.2 out. It was also noted that this was the first release where community testing was requested and the community came through. 
- v3.2.1 (@punkrokk / @blag ) - a bug and security fix release. TSC and community came together to address these, will likely cut a release later in May.
- @punkrokk suggested that ST2 codify a vulnerability/bug response process at a high level, every one agreed in spirit, although there was some discussion around the level of detail required for this. @punkrokk agreed to propose something soon.
- The tech debt in the ST2 front end was discussed and there are some individuals who have stepped up to offer to contribute. TSC will work on finding an owner to consider managing this.
- There was some discussion, but no decisions around the order of operations of the following items:
  * Python 2.7 removal
  * Ubuntu 16 (deprecation/py3)
  * Ubuntu 20 (requires python 3.8)
  * Other things that are desired to be incorporated into ST2 core through out the rest of 2020
- There will be a **python 2.7 removal committee** formed and a call for volunteers made with a first meeting in ~ 2 weeks.

**Comment by armab** [comment]
One of the discussed topics that's missing here is how we should react on Security issues and having a better framework around it.



To give more context and history, there are 2 CVEs that we ever filled for StackStorm and patch releases came from that: 
- https://stackstorm.com/2018/12/20/stackstorm-v2-9-2-and-v2-10-1-a-security-release/
- https://stackstorm.com/2019/03/08/stackstorm-2-9-3-2-10-3/


Here are the additional resources describing how StackStorm handles security:
- https://stackstorm.com/security/
- https://docs.stackstorm.com/security.html
- https://github.com/StackStorm/st2/blob/master/SECURITY.md

With that, there is already strong framework around security, describing how bugs should be reported and which channels used, what's the response time from the team, Responsible Disclosure, and so on.

@punkrokk as discussed during the TSC meeting, please provide a PR with the proposals & enhancements for https://github.com/StackStorm/st2/blob/master/SECURITY.md or st2docs to improve the existing docs and so we could review it and talk more concretely.
