### ISSUE TITLE
Proposal: Deploy packs using StackStorm instead of CircleCI

### ISSUE THREAD

**Issue by blag** [StackStorm/community#29]
Sometimes we have to update the CircleCI configurations for all Exchange packs, and this is very tedious since our scripts have to wait for the `deploy` step of the CircleCI run for each pack to finish before merging the next PR or branch and kicking off another CircleCI run.

Some examples of where this is required:

* StackStorm/discussions#22
* [Adding `apt update` to bust the apt cache for the `deploy` step](https://github.com/StackStorm-Exchange/stackstorm-aws/commit/5531d718d89220ec1d39f825cab734b4e2146afb)
* [Add and declare Python 3 support to all Exchange packs](https://github.com/StackStorm-Exchange/stackstorm-aws/pull/92)
* [Block deployment on both Python 2 and Python 3 tests passing](https://github.com/StackStorm-Exchange/stackstorm-aws/pull/97)
* Update `requests` version
* Remove Python 2 support (in the future)

**Comment by armab** [comment]
Yes, there are problems with the missing locking and synchronization for the index file when building many packs in parallel which could be improved.
 
However it's important the way how StackStorm-Exchange was built, open, transparent and self-sufficient based on free CircleCI and requiring no additional infrastructure. Additionally,  
Anyone could just clone our system and enable CircleCI without the need to spin-up a dedicated StackStorm instance for it and avoiding complexity.

**Comment by armab** [comment]
Talking about the Deployment and index synchronization issue for StackStorm-Exchange,
looking at the CircleCI config this could be improved so we minimize the problem making races really rare to hit.

Here is how to do that:

### Minimize the Exchange index conflict
  - this is achievable by making the index update taking minimum possible time (~ around 1 second or so)
  - We should re-download index on deployment step before re-generating it updating/pushing it. This means the time window when the race/conflict possible is around second or so.
  - pushing outdated index shows as git conflict and deployment job failure should be safely restarted, see below
### Make deployment operations idempotent
  - write all the steps in deployment step so they're fully idempotent
    - if deploy failed due to index conflict, - re-starting the deployment step will lead to retry for the failed operation, skipping all the previous steps that were successful
    - run the deployment step 2 times `deploy || deploy` to minimize human if deployment failed due to index conflict

This way we can minize the StackStorm-Exchange pack deployment issues up to state when human interruption is almost not needed. Some of those steps are already in-place in the current deployment step, so this should be fairly simple change and a quick win.

**Comment by armab** [comment]
### Alternative conflict-free approach: Push isolated per-pack index update from each Deployment
- instead of every pack pushing the change to main `index.json`, let them push isolated per-pack index meta, there is already dir for that: https://github.com/StackStorm-Exchange/index/tree/master/v1/packs
- Setup every minute CircleCI cron job that will iterate over the pack dirs with their meta indexes and generate main StackStorm-Exchange index if there is a diff.

^^ This will require more work comparing to previous enhancement, but this approach removes the possibility of index conflict.

So there are plenty of options making things simple, working and self-sufficient, instead of relying on external StackStorm or lock-control instance.

**Comment by cognifloyd** [comment]
We have moved Exchange CI to GHA away from CircleCI, so I think we can close this.

**Comment by arm4b** [comment]
Good call, agreed :100:
