### ISSUE TITLE
TSC Meeting (02 June 2020) Agenda and Minutes: ChatOps Survey, Integrating EWC Components, v3.2.1 patch release

### ISSUE THREAD

**Issue by blag** [StackStorm/community#31]
# TSC Agenda June 2nd, 5:30pm UTC, 12:30pm EDT, 9:30am PDT

## Administrative Discussions/Announcements ##

* [ ] Questions for/comments from Ravi
* [x] Linux Foundation Updates
  - [x] See discussion #32 
  - [x] RFC: LF desires ST2 project to possibly use [EasyCLA](https://lfcla.com/) (Charter says we just need CLA management, not Easy CLA specifically)
  - [x] Community Bridge -> Sponsoring
  - [x] Update Charter
  - [x] Open Up TSC meetings
* [x] What are the expectations of TSC members? 
* [x] Should we split up TSC and Sprint Planning?
  - [x] @punkrokk proposes a 12 month term for a person to run the TSC. If we have a new person each month it sacrifices continuity with rotating work.
  - [x] Or should the next release manager/s run the TSC meetings?
* [x] Next meeting is July 7th, 2020
  - [x] Notify everybody that it be public
  - [x] Discuss how to invite community members to particpate

-------------------------------------

## Discussions left for next meeting ##

* [ ] Integrating EWC components
  - [ ] st2flow -> st2web
    + [ ] How to handle VCS integration?
      * [ ] Electron app that uses git on user's local machine?
      * [ ] Have ST2 add a commit in pack repo in `/opt/stackstorm/packs/`?
      * [ ] Automatic push to git remote + open a PR?
  - [ ] Apt/RPM packaging for LDAP/RBAC/SSO plugins? Or just roll them into `st2` package?
  - [ ] Any additional EWC OSS transition questions
* [ ] Revisit v3.3 proposed featureset (@blag, @punkrokk)
* [ ] Review status of proposed new contributors

## Technical Discussions ##

* [x] ChatOps Survey (@blag)
  - [x] Survey Monkey?
  - [ ] Who is paying for this/can we get LF to pay for this?
* [ ] Discuss [`v3.2.1` patch release](https://github.com/orgs/StackStorm/projects/10) - @punkrokk

**Comment by armab** [comment]
- `v3.2.1` patch release (https://github.com/orgs/StackStorm/projects/10) (@punkrokk)
- Ravi from Extreme should join us to answer any EWC OSS transition questions

FYI we should also plan to open our monthly TSC meetings, likely from the next one July 7th, 2020, per LF requirement.

**Comment by blag** [comment]
# TSC Meeting Minutes #

## Changing copyright headers ##

* Needs to be done or at least approved by somebody at Extreme Networks
* Need to add Linux Foundation to copyright claims
* Need to have a template for copyright headers on new files?

### DECIDED ###

* For Apache 2.0 License:
  - Add one line to the copyright section of every file that has a header.
  - Do not remove it.
  - Winson will approve the PRs

## Linux Foundation Updates ##

* May need to change the CLA to be in alignment with LF
* Don't necessarily need to change to EasyCLA
  - Don't like it because it forces clickthroughs for every single commit
  - Needs more research into wording in technical charter

### LF Community Bridge approved ###

* provides a way for people to donate to project
* provides a way for us to expense it
  - Zoom
  - ChatOps User Survey with Survey Monkey
* Plan is to make announcement about it

* Dmitri will update ActiveCampaign list, and send out another email regarding LF donations
* Ping Dmitri when we update the blog, so he can blast out emails on ActiveCampaign

## Opening up TSC Meetings ##

* Use LF "TSC Open" mailing list to announce meetings and invite spectators
* Use LF "TSC Closed" mailing list to record votes and keep LF folks up-to-date

## How to run TSC meetings? ##

* Do we want a different person running every TSC meeting?
  - Do we want to appoint a TSC chairperson to run all TSC meetings?
    + Continuity is important - difficult to parachute into an issue

  - It might be good for each TSC member to do a lap of running TSC meetings

* 12 months is too long of a period for one person to run meetings
* 3 months is the minimum length
* 6 months seems about right

* Do we want to split up meetings into 1 monthly administrative meeting and 1 technical meeting?

### DECIDED ###

* Eugen running TSC meetings for the next 3 months - THANK YOU!
  - JP and Nick will informally help do the sprint planning
  - will revisit how this is working in 3 months

## Expectations of TSC members ##

* What is the bare minimum?
  - At what point do we vote to take action on another community member?

### DECIDED ###

* Tabled - moving discussion to the next meeting
  - JP will consolidate the concerns

## ChatOps User Survey ##

* How many people?
  - Target is to get 100+ responses
  - Below 50 responses, results aren't super useful
  - Check out the previous ChatOps User Survey

**Comment by timfong888** [comment]
Is there an Issue for July’s agenda?

**Comment by armab** [comment]
We'll create one a several days before the July meeting as composing agenda right now is too early and things may change.
