### ISSUE TITLE
[Proposal] - Updated License Headers per LF Guidance

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/community#32]
Per guidance from LF we should update our [License Headers](https://github.com/StackStorm/st2/blob/1c75443dd917e63b4d195fec2b13d675a5c7238b/st2reactor/st2reactor/sensor/base.py#L1) with the following string:

Just add the below line to each file header
```
"Copyright 2020 by the contributors to the Stackstorm Project a Series of LF Projects, LLC"
```

Questions: 
- [x] For former EWC contributed repos, do we need to keep the EWC Copyright page? How to this change over time as the code file changes? Yes. 

- [ ] We will probably need to create a project just for this task as it affects just about every repo. 

- [ ] Will we also need to update stackstorm exchange? 

- [ ] Extreme employee to "approve" the licensing change. Need a PR for each repo which Changes the License to apache 2.0.

**Comment by cognifloyd** [comment]
Also, who is allowed to make this change?
For all the newly-open-sourced stuff, we probably need someone from ExtremeNetworks to do at least adjust the license.
For all the other repos, I could go through and make a few mass PRs. Or would someone else have to do that?
