### ISSUE TITLE
Align resources within the Linux Foundation infrastructure

### ISSUE THREAD

**Issue by timfong888** [StackStorm/community#34]
As part of the LF, there are other components, that I'd like to discuss whether we do them or not.  These are the standard administrative items we have for projects.

- [ ] Google Analytics -- the LF have access to administer

- [x] Domain and Alias: our IT department can instrument into our itx.linuxfoundation.org service

- [x] Slack admin access: also LF 

- [x] GitHub admin access to support webhooks and administration in itx.linuxfoundation.org

- [x] Via Github: instrument for developer insights analytics

- [ ] Forums access -- same

- [ ] Email forum -- we are using across the LF groups.io for email based mailing lists....BUT if everything is taking place in slack or GitHub currently, no need to force something people definitely will not use

- [ ] Marketing campaign tooling: -- LF access

- [ ] Other things to help with transition?

- [x] Checking on Zoom access for unfunded projects.

**Comment by armab** [comment]
Let's move it into Email thread.
There is some process already happening with the Linux Foundation and this effort will complement it.

**Comment by arm4b** [comment]
For the curious souls, StackStorm project development Analytics by the Linux Foundation is available at:
https://lfanalytics.io/projects/stackstorm/dashboard
